# Generated by Django 4.1 on 2022-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='acount',
            field=models.EmailField(max_length=254),
        ),
    ]
