# Generated by Django 4.1 on 2022-10-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_alter_staff_acount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='acount',
            new_name='account',
        ),
    ]
