# Generated by Django 4.1 on 2022-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
