# Generated by Django 4.1 on 2022-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_alter_message_email_alter_message_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
